# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription(f13ba1dc-c21b-41bf-bc7d-1b4e8e91e6e6)'
    subscriptionId: 'f13ba1dc-c21b-41bf-bc7d-1b4e8e91e6e6'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'quickstart-vm-dc2'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/imranrafique384/arm-project01/main/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/imranrafique384/arm-project01/main/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'